# Generated by Django 5.2.7 on 2025-11-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyJourney', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='admin_screenshots/')),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
    ]
