# Generated by Django 5.2.7 on 2025-11-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyJourney', '0002_adminscreenshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminScreenshot',
        ),
    ]
