# Generated by Django 5.2.7 on 2025-11-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyJourney', '0003_delete_adminscreenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='admin_screenshots/')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='aboutme',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
